# Generated by Django 4.2.7 on 2025-07-05 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=255, verbose_name='especialidad')),
                ('fecha_contratacion', models.DateField(verbose_name='fecha de contratación')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='docentes/fotos/', verbose_name='foto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_docente', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'docente',
                'verbose_name_plural': 'docentes',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
