# Generated by Django 4.2.7 on 2025-07-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='descripción'),
        ),
    ]
