# Generated by Django 4.2.7 on 2025-07-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('orden', models.IntegerField(default=0, help_text='Para ordenar en listas', verbose_name='orden')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('es_nivel_superior', models.BooleanField(default=False, help_text='Para diferenciar niveles universitarios', verbose_name='es nivel superior')),
            ],
            options={
                'verbose_name': 'nivel educativo',
                'verbose_name_plural': 'niveles educativos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('duracion', models.CharField(blank=True, help_text="Ejemplo: '3 años', '1 semestre', '4 semanas'", max_length=50, verbose_name='duración')),
                ('es_temporal', models.BooleanField(default=False, help_text='¿Es un curso temporal como un curso de verano?', verbose_name='es temporal')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='core.educationallevel', verbose_name='nivel educativo')),
            ],
            options={
                'verbose_name': 'programa académico',
                'verbose_name_plural': 'programas académicos',
                'ordering': ['nivel_educativo__orden', 'nombre'],
                'unique_together': {('nombre', 'nivel_educativo')},
            },
        ),
    ]
