# Generated by Django 4.2.7 on 2025-07-06 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_educationallevel_academicprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'catálogo',
                'verbose_name_plural': 'catálogos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('orden', models.IntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'género',
                'verbose_name_plural': 'géneros',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100, verbose_name='valor')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('orden', models.IntegerField(default=0, help_text='Para ordenar en listas', verbose_name='orden')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.catalogo', verbose_name='catálogo')),
            ],
            options={
                'verbose_name': 'elemento de catálogo',
                'verbose_name_plural': 'elementos de catálogo',
                'ordering': ['catalogo', 'orden', 'valor'],
                'unique_together': {('catalogo', 'valor')},
            },
        ),
    ]
