# Generated by Django 4.2.7 on 2025-07-10 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_catalogo_genero_catalogoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('VIEW', 'Ver'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar'), ('DOWNLOAD', 'Descargar'), ('UPLOAD', 'Subir'), ('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar'), ('ASSIGN', 'Asignar'), ('UNASSIGN', 'Desasignar')], max_length=20, verbose_name='Acción')),
                ('module', models.CharField(choices=[('USERS', 'Usuarios'), ('ALUMNOS', 'Alumnos'), ('DOCENTES', 'Docentes'), ('ASISTENCIA', 'Asistencia'), ('PLANES_ESTUDIO', 'Planes de Estudio'), ('WORKCENTER', 'Centro de Trabajo'), ('MATRICULAS', 'Matrículas'), ('REPORTES', 'Reportes'), ('CONTROL_ESCOLAR', 'Control Escolar'), ('SYSTEM', 'Sistema')], max_length=20, verbose_name='Módulo')),
                ('object_type', models.CharField(max_length=100, verbose_name='Tipo de Objeto')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del Objeto')),
                ('object_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Objeto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='Datos Adicionales')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividades',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_activi_user_id_81b1f1_idx'), models.Index(fields=['action', 'timestamp'], name='core_activi_action_549521_idx'), models.Index(fields=['module', 'timestamp'], name='core_activi_module_a92616_idx'), models.Index(fields=['timestamp'], name='core_activi_timesta_44c73d_idx')],
            },
        ),
    ]
