# Generated by Django 4.2.7 on 2025-07-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('T', 'Tarde'), ('A', 'Ausente')], default='P', max_length=1, verbose_name='estado')),
                ('hora_entrada', models.TimeField(verbose_name='hora de entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='hora de salida')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='alumnos.alumno', verbose_name='alumno')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='docentes.docente', verbose_name='docente')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'ordering': ['-fecha', 'alumno__user__last_name'],
            },
        ),
    ]
