# Generated by Django 4.2.7 on 2025-07-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(verbose_name='fecha de fin')),
            ],
            options={
                'verbose_name': 'ciclo escolar',
                'verbose_name_plural': 'ciclos escolares',
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('address', models.TextField(verbose_name='dirección')),
                ('director_name', models.CharField(max_length=100, verbose_name='nombre del director')),
                ('school_control_name', models.CharField(max_length=100, verbose_name='nombre del control escolar')),
            ],
            options={
                'verbose_name': 'centro de trabajo',
                'verbose_name_plural': 'centros de trabajo',
            },
        ),
        migrations.CreateModel(
            name='SchoolPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('period_type', models.CharField(choices=[('BIMESTER', 'Bimestre'), ('TRIMESTER', 'Trimestre'), ('SEMESTER', 'Semestre'), ('ANNUAL', 'Anual')], max_length=10, verbose_name='tipo de período')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(verbose_name='fecha de fin')),
                ('school_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcenter.schoolcycle', verbose_name='ciclo escolar')),
            ],
            options={
                'verbose_name': 'periodo escolar',
                'verbose_name_plural': 'periodos escolares',
            },
        ),
        migrations.AddField(
            model_name='schoolcycle',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcenter.workcenter', verbose_name='centro de trabajo'),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='capacidad')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcenter.workcenter', verbose_name='centro de trabajo')),
            ],
            options={
                'verbose_name': 'aula',
                'verbose_name_plural': 'aulas',
            },
        ),
    ]
