# Generated by Django 4.2.7 on 2025-07-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcycle',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica si este ciclo está activo', verbose_name='activo'),
        ),
        migrations.CreateModel(
            name='SchoolCycleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_multiple_active', models.BooleanField(default=False, help_text='Permite tener múltiples ciclos activos simultáneamente', verbose_name='permitir múltiples ciclos activos')),
                ('auto_activate_by_date', models.BooleanField(default=True, help_text='Activa automáticamente los ciclos según las fechas', verbose_name='activación automática por fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('work_center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_config', to='workcenter.workcenter', verbose_name='centro de trabajo')),
            ],
            options={
                'verbose_name': 'configuración de ciclos',
                'verbose_name_plural': 'configuraciones de ciclos',
            },
        ),
    ]
