# Generated by Django 4.2.7 on 2025-07-05 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('numero_cuenta', models.CharField(max_length=20, unique=True, verbose_name='número de cuenta')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alumnos/fotos/', verbose_name='foto')),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_alumnos', to='core.carrera', verbose_name='carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_alumno', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'alumno',
                'verbose_name_plural': 'alumnos',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
