# Generated by Django 4.2.7 on 2025-07-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_educationallevel_academicprogram'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='carrera',
        ),
        migrations.AddField(
            model_name='alumno',
            name='programa_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='core.academicprogram', verbose_name='programa académico'),
        ),
    ]
