# Generated by Django 4.2.7 on 2025-07-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workcenter', '0002_schoolcycle_is_active_schoolcycleconfig'),
        ('alumnos', '0002_remove_alumno_carrera_alumno_programa_academico'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='workcenter.workcenter', verbose_name='centro de trabajo'),
        ),
    ]
