# Generated by Django 4.2.7 on 2025-07-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_work_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='numero_cuenta',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='número de cuenta'),
        ),
    ]
