# Generated by Django 4.2.7 on 2025-07-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alter_alumno_numero_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curp',
            field=models.CharField(blank=True, help_text='Clave Única de Registro de Población', max_length=18, null=True, unique=True, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre_contacto_emergencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='nombre del contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono_contacto',
            field=models.CharField(blank=True, help_text='Número de teléfono para contacto', max_length=15, verbose_name='teléfono de contacto'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono_contacto_emergencia',
            field=models.CharField(blank=True, max_length=15, verbose_name='teléfono del contacto de emergencia'),
        ),
    ]
