# Generated by Django 4.2.7 on 2025-07-06 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_catalogo_genero_catalogoitem'),
        ('alumnos', '0005_alumno_curp_alumno_nombre_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='core.genero', verbose_name='género'),
        ),
    ]
