# Generated by Django 4.2.7 on 2025-07-06 01:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('workcenter', '0002_schoolcycle_is_active_schoolcycleconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('duracion_semestres', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='duración en semestres')),
                ('creditos_totales', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='créditos totales')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20, verbose_name='estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='core.carrera', verbose_name='carrera')),
                ('ciclo_inicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_inicio', to='workcenter.schoolcycle', verbose_name='ciclo de inicio')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='workcenter.workcenter', verbose_name='centro de trabajo')),
            ],
            options={
                'verbose_name': 'plan de estudios',
                'verbose_name_plural': 'planes de estudios',
                'unique_together': {('carrera', 'work_center', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='SemestrePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semestre', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número de semestre')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('creditos_semestre', models.PositiveIntegerField(default=0, verbose_name='créditos del semestre')),
                ('es_optativo', models.BooleanField(default=False, verbose_name='es optativo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='planes_estudio.planestudio', verbose_name='plan de estudios')),
            ],
            options={
                'verbose_name': 'semestre del plan',
                'verbose_name_plural': 'semestres del plan',
                'ordering': ['numero_semestre'],
                'unique_together': {('plan_estudio', 'numero_semestre')},
            },
        ),
        migrations.CreateModel(
            name='PerfilEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_general', models.TextField(verbose_name='descripción general')),
                ('competencias_generales', models.TextField(verbose_name='competencias generales')),
                ('competencias_especificas', models.TextField(verbose_name='competencias específicas')),
                ('campo_laboral', models.TextField(verbose_name='campo laboral')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('plan_estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_egreso', to='planes_estudio.planestudio', verbose_name='plan de estudios')),
            ],
            options={
                'verbose_name': 'perfil de egreso',
                'verbose_name_plural': 'perfiles de egreso',
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='orden')),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_educativos', to='planes_estudio.planestudio', verbose_name='plan de estudios')),
            ],
            options={
                'verbose_name': 'objetivo educativo',
                'verbose_name_plural': 'objetivos educativos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_materia', models.CharField(choices=[('OBLIGATORIA', 'Obligatoria'), ('OPTATIVA', 'Optativa'), ('COMPLEMENTARIA', 'Complementaria')], default='OBLIGATORIA', max_length=20, verbose_name='tipo de materia')),
                ('creditos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='créditos')),
                ('horas_teoria', models.PositiveIntegerField(default=0, verbose_name='horas de teoría')),
                ('horas_practica', models.PositiveIntegerField(default=0, verbose_name='horas de práctica')),
                ('horas_independiente', models.PositiveIntegerField(default=0, verbose_name='horas independiente')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de la materia dentro del semestre', verbose_name='orden')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia', verbose_name='materia')),
                ('prerequisitos', models.ManyToManyField(blank=True, to='planes_estudio.materiaplan', verbose_name='prerrequisitos')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='planes_estudio.semestreplan', verbose_name='semestre')),
            ],
            options={
                'verbose_name': 'materia del plan',
                'verbose_name_plural': 'materias del plan',
                'ordering': ['orden'],
                'unique_together': {('semestre', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('tipo_competencia', models.CharField(choices=[('GENERICA', 'Genérica'), ('ESPECIFICA', 'Específica'), ('TRANSVERSAL', 'Transversal')], default='ESPECIFICA', max_length=20, verbose_name='tipo de competencia')),
                ('materias', models.ManyToManyField(blank=True, related_name='competencias', to='planes_estudio.materiaplan', verbose_name='materias')),
            ],
            options={
                'verbose_name': 'competencia',
                'verbose_name_plural': 'competencias',
            },
        ),
        migrations.CreateModel(
            name='VersionPlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField(verbose_name='número de versión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('cambios_descripcion', models.TextField(blank=True, verbose_name='descripción de cambios')),
                ('es_activa', models.BooleanField(default=True, verbose_name='es activa')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='planes_estudio.planestudio', verbose_name='plan de estudios')),
            ],
            options={
                'verbose_name': 'versión del plan',
                'verbose_name_plural': 'versiones del plan',
                'ordering': ['-numero_version'],
                'unique_together': {('plan_estudio', 'numero_version')},
            },
        ),
    ]
